'use client'

import { Bar, BarChart, CartesianGrid, XAxis, YAxis } from 'recharts'
import {
  ChartContainer,
  ChartLegend,
  ChartLegendContent,
  ChartTooltip,
  ChartTooltipContent,
  type ChartConfig,
} from '@/components/ui/chart'
import type { CategoryMonthRow } from '@/lib/csv'
import { ChartFrame, ChartEmpty } from './ChartFrame'

interface CategoryTrendProps {
  data: CategoryMonthRow[]
}

const PALETTE = [
  'var(--chart-1)',
  'var(--chart-2)',
  'var(--chart-3)',
  'var(--chart-4)',
  'var(--chart-5)',
  'var(--muted-foreground)',
  'var(--primary)',
]

// Category names contain spaces and "&"; slugify so CSS custom-prop names
// (--color-<key>) generated by ChartContainer stay valid.
function slug(s: string): string {
  return s.replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '').toLowerCase()
}

function shortMonth(key: string): string {
  if (!/^\d{4}-\d{2}$/.test(key)) return key
  const [y, m] = key.split('-').map(Number)
  return new Date(y, m - 1, 1).toLocaleDateString('en-MY', { month: 'short' })
}

export default function CategoryTrend({ data }: CategoryTrendProps) {
  const hasExpense = data.some((row) =>
    Object.entries(row).some(([k, v]) => k !== 'month' && typeof v === 'number' && v > 0)
  )
  if (data.length === 0 || !hasExpense) {
    return <ChartEmpty title="Spending by category · 6 months" />
  }

  const categories = Object.keys(data[0]).filter((k) => k !== 'month')
  // Build unique slugs. Distinct categories can slug to the same string
  // (e.g. the real "other" category and the "Other" tail bucket both -> "other"),
  // which would collide as CSS vars, dataKeys, and React keys — overwriting data.
  const usedSlugs = new Set<string>()
  const keyToSlug = new Map<string, string>()
  for (const c of categories) {
    const base = slug(c) || 'cat'
    let s = base
    let n = 2
    while (usedSlugs.has(s)) s = `${base}-${n++}`
    usedSlugs.add(s)
    keyToSlug.set(c, s)
  }

  const config: ChartConfig = Object.fromEntries(
    categories.map((c, i) => [
      keyToSlug.get(c)!,
      { label: c, color: PALETTE[i % PALETTE.length] },
    ])
  )

  const chartData = data.map((row) => {
    const out: Record<string, number | string> = { month: shortMonth(String(row.month)) }
    for (const c of categories) out[keyToSlug.get(c)!] = (row[c] as number) ?? 0
    return out
  })

  return (
    <ChartFrame title="Spending by category · 6 months">
      <ChartContainer config={config} className="h-[260px] w-full">
        <BarChart data={chartData} margin={{ left: 4, right: 12, top: 8, bottom: 4 }}>
          <CartesianGrid vertical={false} stroke="var(--border)" />
          <XAxis dataKey="month" tickLine={false} axisLine={false} tickMargin={8} fontSize={11} />
          <YAxis
            tickFormatter={(v: number) => `RM ${v}`}
            tickLine={false}
            axisLine={false}
            width={64}
            fontSize={11}
          />
          <ChartTooltip content={<ChartTooltipContent />} />
          <ChartLegend content={<ChartLegendContent />} />
          {categories.map((c) => {
            const s = keyToSlug.get(c)!
            return <Bar key={s} dataKey={s} stackId="a" fill={`var(--color-${s})`} />
          })}
        </BarChart>
      </ChartContainer>
    </ChartFrame>
  )
}
